backlogext/urls.py
from django.urls import path
from .views import auth, issue, api, setting

app_name = 'backlogext'

urlpatterns = [
    # guest user
    ## auth
    path('signup/', auth.Signup.as_view(), name='signup'),
    path('login/', auth.Login.as_view(), name='login'),

    # auth user
    ## auth
    path('logout/', auth.Logout.as_view(), name='logout'),
    ## issue
    path('issue_list', issue.IssueListView.as_view(), name='issue_list'),
    path('issue_create', issue.IssueCreateView.as_view(), name='issue_create'),
    path('issue_detail/<int:pk>/', issue.IssueDetailView.as_view(), name='issue_detail'),
    path('issue_update/<int:pk>/', issue.IssueUpdateView.as_view(), name='issue_update'),
    path('issue_delete/<int:pk>/', issue.IssueDeleteView.as_view(), name='issue_delete'),
    ## api
    path('create_issue', api.create_issue, name='create_issue'),
    path('authenticate_success', api.authenticate_success, name='authenticate_success'),
    ## setting
    path('setting_create', setting.SettingCreateView.as_view(), name='setting_create'),
    path('setting_update/<int:pk>/', setting.SettingUpdateView.as_view(), name='setting_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backlogext.urls')),
]

nulabproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backlogext/', include('backlogext.urls')),
]

backlogext/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Issue(models.Model):
    key_id = models.IntegerField('課題キー', blank=True, null=True)
    type_id = models.IntegerField('課題種別キー', blank=True, null=True)
    project_id = models.IntegerField('project id', blank=True, null=True)
    project_key = models.CharField('project key', max_length=255, blank=True, null=True)
    summary = models.CharField('件名', max_length=255)
    description = models.TextField('詳細')
    created_at = models.DateTimeField('作成日時', auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.summary
    
class Token(models.Model):
    access_token = models.CharField('token', max_length=255, blank=True, null=True)
    refresh_token = models.CharField('refresh_token', max_length=255, blank=True, null=True)
    expires_in = models.IntegerField('expires_in', blank=True, null=True)
    updated_at = models.DateTimeField('updated_at', auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.access_token
    
class Setting(models.Model):
    space_key = models.CharField('space key', max_length=255)
    domain = models.CharField('domain', max_length=255, blank=True, null=True)
    project_key = models.CharField('project key', max_length=255)
    project_id = models.IntegerField('project id', blank=True, null=True)
    code = models.CharField('code', max_length=255, blank=True, null=True)
    client_id = models.CharField('client id', max_length=255)
    client_secret = models.CharField('client secret', max_length=255)
    updated_at = models.DateTimeField('updated_at', auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.space_key

backlogext/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Issue, Setting

User = get_user_model()

class IssueCreateForm(forms.ModelForm):
    type_id = forms.ChoiceField()

    def __init__(self, type_choices=None, *args, **kwargs):
        self.base_fields['type_id'].choices = type_choices
        super(IssueCreateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Issue
        fields = ('type_id', 'summary', 'description')

class SettingCreateForm(forms.ModelForm):
    domain = forms.ChoiceField()

    def __init__(self, domain_choices=None, *args, **kwargs):
        self.base_fields['domain'].choices = domain_choices
        super(SettingCreateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Setting
        fields = ('space_key', 'domain', 'project_key', 'project_id', 'client_id', 'client_secret')

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

backlogext/views/api.py
from django.shortcuts import redirect
from backlogext.models import Setting
from backlogext.src.api import Api
from backlogext.src.util import Util
from backlogext.src.db import Db
from django.contrib import messages


def authenticate_success(request):
    """oauth2の認可コード取得完了時の処理を行う"""

    api = Api(request.user)
    db = Db(request.user)

    db.update_setting_code(request.GET['code'])
    json_response = api.create_token(request.GET['code'])

    if 'errors' in json_response:
        messages.info(request, f'エラーが発生しました。時間をおいて再度実行してください。')
        return redirect('/issue_list')

    db.update_token(json_response)

    messages.info(request, f'backlogとの連携が完了しました。操作をやり直してください。')
    return redirect('/issue_list')

def create_issue(request):
    """課題をbacklogに追加する"""
    api = Api(request.user)
    util = Util(request.user)
    db = Db(request.user)
    
    # 認可コードが存在しない場合、認可コードを取得する
    setting = Setting.objects.get(user=request.user.id)
    if not setting.code:
        return redirect(util.get_authentication_code_url())

    # 課題追加をbacklogにリクエストする
    header = util.get_headers(request.user)
    body = {
        'projectId': request.POST['projectId'],
        'summary': request.POST['summary'],
        'issueTypeId': request.POST['issueTypeId'],
        'priorityId': request.POST['priorityId'],
    }
    json_response = api.create_issue(header, body)

    if 'errors' in json_response:
        messages.info(request, f'エラーが発生しました。時間をおいて再度実行してください。')
        return redirect('/issue_list')

    # 課題キーをセットする
    db.update_issue(json_response, request.POST['pk'])

    messages.info(request, f'backlogに課題を追加しました')
    return redirect('/issue_list')

backlogext/views/issue.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from backlogext.models import Issue, Setting
from backlogext.forms import IssueCreateForm
from backlogext.src.api import Api
from backlogext.src.util import Util


class IssueListView(generic.ListView):
    """課題一覧ページ"""
    template_name = 'backlogext/issue_list.html'

    # settingを追加
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        try:
            ctx['setting'] = Setting.objects.get(user=self.request.user.id)
        except Setting.DoesNotExist:
            ctx['setting'] = None
            print('no setting')
        
        return ctx
    
    # ユーザに紐づくissueを表示
    def get_queryset(self):
        current_user = self.request.user
        if current_user.is_superuser:
            issue = Issue.objects.all()
        else:
            issue = Issue.objects.filter(user=current_user.id)

        return issue.order_by('-id')

class IssueCreateView(generic.CreateView):
    """課題作成ページ"""
    template_name = 'backlogext/issue_form.html'
    form_class = IssueCreateForm
    success_url = reverse_lazy('backlogext:issue_list')

    # settingが存在しない場合、setting_createにリダイレクトする
    def get(self, request, *args, **kwargs):
        try:
            setting = Setting.objects.get(user=self.request.user.id)
        except Setting.DoesNotExist:
            messages.info(request, f'はじめに設定をしてください')
            return redirect('/setting_create')
        
        # 認可コードが存在しない場合、認可コードを取得する
        if not setting.code:
            util = Util(self.request.user)
            return redirect(util.get_authentication_code_url())
            
        return super().get(request, *args, **kwargs)

    # user, project_key, project_idを追加
    def form_valid(self, form):
        setting = Setting.objects.get(user=self.request.user.id)
        q = form.save(commit=False)
        q.user = self.request.user
        q.project_key = setting.project_key
        q.project_id = setting.project_id
        q.save()
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(IssueCreateView, self).get_form_kwargs()

        user = self.request.user
        api = Api(user)
        util = Util(user)
        self.header = util.get_headers(user)
        self.issue_types = api.get_issue_types(self.header)
        type_choices = [(issue_type['id'], issue_type['name']) for issue_type in self.issue_types]
        kwargs['type_choices'] = type_choices

        return kwargs

class IssueDetailView(generic.DetailView):
    """課題詳細ページ"""
    template_name = 'backlogext/issue_detail.html'
    model = Issue
    
class IssueUpdateView(generic.UpdateView):
    """課題更新ページ"""
    template_name = 'backlogext/issue_form.html'
    model = Issue
    form_class = IssueCreateForm
    success_url = reverse_lazy('backlogext:issue_list')

    def get_form_kwargs(self):
        kwargs = super(IssueUpdateView, self).get_form_kwargs()

        user = self.request.user
        api = Api(user)
        util = Util(user)
        self.header = util.get_headers(user)
        self.issue_types = api.get_issue_types(self.header)
        type_choices = [(issue_type['id'], issue_type['name']) for issue_type in self.issue_types]
        kwargs['type_choices'] = type_choices

        return kwargs

class IssueDeleteView(generic.DeleteView):
    """課題削除ページ"""
    template_name = 'backlogext/issue_confirm_delete.html'
    model = Issue
    success_url = reverse_lazy('backlogext:issue_list')

backlogext/views/setting.py
from django.urls import reverse_lazy
from django.views import generic
from backlogext.models import Setting
from backlogext.forms import SettingCreateForm
from django.shortcuts import redirect

DOMAIN_CHOICES = [
    ('backlog.jp', 'backlog.jp'),
    ('backlog.com', 'backlog.com'),
    ]

class SettingCreateView(generic.CreateView):
    """設定作成ページ"""
    template_name = 'backlogext/setting_form.html'
    form_class = SettingCreateForm
    success_url = reverse_lazy('backlogext:issue_list')

    # settingが存在する場合、setting_updateにリダイレクトする
    def get(self, request, *args, **kwargs):
        try:
            setting = Setting.objects.get(user=self.request.user.id)
        except Setting.DoesNotExist:
            return super().get(request, *args, **kwargs)
        
        return redirect(f'/setting_update/{setting.pk}')
            
    # userを追加
    def form_valid(self, form):
        q = form.save(commit=False)
        q.user = self.request.user
        q.save()
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(SettingCreateView, self).get_form_kwargs()
        kwargs['domain_choices'] = DOMAIN_CHOICES
        return kwargs

class SettingUpdateView(generic.UpdateView):
    """設定更新ページ"""
    template_name = 'backlogext/setting_form.html'
    model = Setting
    form_class = SettingCreateForm
    success_url = reverse_lazy('backlogext:issue_list')

    def get_form_kwargs(self):
        kwargs = super(SettingUpdateView, self).get_form_kwargs()
        kwargs['domain_choices'] = DOMAIN_CHOICES
        return kwargs

templates/backlogext/issue_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    <table>
        <tr>
          <th>件名</th>
          <td>{{ issue.summary }}</td>
        </tr>
        <tr>
          <th>詳細</th>
          <td>{{ issue.description }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

templates/backlogext/issue_detail.html
{% extends 'base.html' %}

{% block content %}
<table>
    <tr>
      <th>件名</th>
      <td>{{ issue.summary }}</td>
    </tr>
    <tr>
      <th>詳細</th>
      <!-- linebreaksbk を入れると改行タグでちゃんと改行して表示されるようになる -->
      <td>{{ issue.description | linebreaksbr}}</td>
    </tr>
</table>
{% endblock %}

templates/backlogext/issue_form.html
{% extends 'base.html' %}

{% block content %}
<p>{{ issue.summary }}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>種別</th>
            <td>{{ form.type_id }}</td>
        </tr>
        <tr>
            <th>件名</th>
            <td>{{ form.summary }}</td>
        </tr>
        <tr>
            <th>詳細</th>
            <td>{{ form.description }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

templates/backlogext/issue_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
    <thead>
        <tr>
            <th>backlogに追加</th>
            <th>ID</th>
            <th>件名</th>
            <th>詳細</th>
        </tr>
    </thead>
    <tbody>
        {% for issue in issue_list %}
        <tr>
            <td>
                {% if issue.key_id %}                    
                    <form action="../issues" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="追加済" disabled>
                    </form>
                {% else %}
                    <form action="{% url 'backlogext:create_issue' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ issue.pk }}">
                        <input type="hidden" name="projectId" value="{{ issue.project_id }}">
                        <input type="hidden" name="summary" value="{{ issue.summary }}">
                        <input type="hidden" name="issueTypeId" value="{{ issue.type_id }}">
                        <input type="hidden" name="priorityId" value="1">
                        <input type="submit" value="追加">
                    </form>
                {% endif %}
            </td>
            <td>
                {% if issue.key_id %}
                    <a href="http://{{ setting.space_key }}.{{ setting.domain }}/view/{{ setting.project_key }}-{{ issue.key_id }}" target="_blank">
                        {{ issue.project_key }}-{{ issue.key_id }}
                    </a>
                {% else %}
                    {{ issue.project_key }}-xx
                {% endif %}
            </td>
            <td><a href="{% url 'backlogext:issue_detail' issue.pk %}">{{ issue.summary }}</a></td>
            <td>{{ issue.description }}</td>
            <td>
                <a href="{% url 'backlogext:issue_update' issue.pk %}">編集</a>
            </td>
            <td>
                <a href="{% url 'backlogext:issue_delete' issue.pk %}">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/backlogext/login.html
{% extends 'base.html' %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-primary text-light">
        <h4>Log in</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            {{ field }}
            {{ field.errors }}
            <br>
          {% endfor %}
          <button type="submit" class="btn btn-primary" >ログイン</button>
          <input type="hidden" name="next" value="{{ next }}" />
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/backlogext/register.html
<h1>Register</h1>

<form method="post">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div>
        <label for="username">Username: </label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="password">Password: </label>
        <input type="password" name="password" id="password" required>
    </div>
    <div>
        <input type="submit" value="register">
    </div>
</form>

templates/backlogext/setting_form.html
{% extends 'base.html' %}

{% block content %}
<p>設定</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>スペース名</th>
            <td>{{ form.space_key }}</td>
        </tr>
        <tr>
            <th>ドメイン</th>
            <td>{{ form.domain }}</td>
        </tr>
        <tr>
            <th>プロジェクト名</th>
            <td>{{ form.project_key }}</td>
        </tr>
        <tr>
            <th>プロジェクトID</th>
            <td>{{ form.project_id }}</td>
        </tr>
        <tr>
            <th>client id</th>
            <td>{{ form.client_id }}</td>
        </tr>
        <tr>
            <th>client secret</th>
            <td>{{ form.client_secret }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

templates/backlogext/user_form.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>{{ process_name }}</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
              {{ field }}
              {{ field.errors }}
            </div>
          {% endfor %}
          {% csrf_token %}
          <!-- ボタン -->
          <button type="button" class="btn btn-outline-secondary btn-lg btn-block mt-4" onclick="history.back()">キャンセル</button>
          <button type="submit" class="btn btn-success btn-lg btn-block mt-2" >{{ process_name }}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}