backlogext/urls.py
from django.urls import path
from .views import auth, issue, api, setting

app_name = 'backlogext'

urlpatterns = [
    # guest user
    ## auth
    path('signup/', auth.Signup.as_view(), name='signup'),
    path('login/', auth.Login.as_view(), name='login'),

    # auth user
    ## auth
    path('logout/', auth.Logout.as_view(), name='logout'),
    ## issue
    path('issue_list', issue.IssueListView.as_view(), name='issue_list'),
    path('issue_create', issue.IssueCreateView.as_view(), name='issue_create'),
    path('issue_detail/<int:pk>/', issue.IssueDetailView.as_view(), name='issue_detail'),
    path('issue_update/<int:pk>/', issue.IssueUpdateView.as_view(), name='issue_update'),
    path('issue_delete/<int:pk>/', issue.IssueDeleteView.as_view(), name='issue_delete'),
    ## api
    path('create_issue', api.create_issue, name='create_issue'),
    path('authenticate_success', api.authenticate_success, name='authenticate_success'),
    ## setting
    path('setting_create', setting.SettingCreateView.as_view(), name='setting_create'),
    path('setting_update/<int:pk>/', setting.SettingUpdateView.as_view(), name='setting_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backlogext.urls')),
]

nulabproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backlogext/', include('backlogext.urls')),
]

templates/base.html
<!doctype html>
<html lang="ja">
<head>
    <title>Backlog Extension</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'backlogext:issue_list' %}">Backlog Extension</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'backlogext:issue_create' %}">課題の追加</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'backlogext:setting_create' %}">設定</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'backlogext:login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'backlogext:signup' %}">会員登録</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'backlogext:logout' %}">ログアウト</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% if messages %}
      {% for message in messages %}
      <p> {{ message }}</p>
      {% endfor %}
    {% endif %}
    
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>